---
 - name: Install Apache jmeter
   hosts: CentosVM2
   become: yes

   vars:
    - tmp_folder: /tmp/Jmeter
    - jmeter_file: apache-jmeter-5.4.tgz
    - tmp_folder_jmeter: apache-jmeter-5.4


   tasks:
## установка java
    - name: Install packages
      yum: 
       name:
        - java
       state: latest

## Создание директорий для загрузки Jmeter

    - name: Create tmp folder
      file: 
        path: "{{tmp_folder}}"
        state: directory
        mode: 0755

#скачиваем исходники такой же версии     
    - name: Download Apache Jmeter
      get_url: 
       url: "https://mirror.datacenter.by/pub/apache.org//jmeter/binaries/{{jmeter_file}}"
       dest: "{{tmp_folder}}"
       mode: 744

    - name: Extract apache-jmeter-5.4.tgz into /tmp/Jmeter
      ansible.builtin.unarchive:
              src: "{{tmp_folder}}/{{jmeter_file}}"
              dest: "{{tmp_folder}}"
              remote_src: yes
#Запуск Apache Jmeter			  
#    - name: Run make modules command  nginx
#      command: "./jmeter-server"
#      args:
#        chdir: "{{tmp_folder}}/{{tmp_folder_jmeter}}/bin"
